export const sampleData = [
  { src: 'dark', alt: 'businessCard_Sample' },
  { src: 'light', alt: 'businessCard_Sample' },
  { src: 'dark', alt: 'businessCard_Sample' },
  { src: 'light', alt: 'businessCard_Sample' },
  { src: 'dark', alt: 'businessCard_Sample' },
  { src: 'light', alt: 'businessCard_Sample' },
  { src: 'dark', alt: 'businessCard_Sample' },
  { src: 'light', alt: 'businessCard_Sample' },
  { src: 'dark', alt: 'businessCard_Sample' },
  { src: 'light', alt: 'businessCard_Sample' },
  { src: 'dark', alt: 'businessCard_Sample' },
  { src: 'light', alt: 'businessCard_Sample' },
  { src: 'dark', alt: 'businessCard_Sample' },
  { src: 'light', alt: 'businessCard_Sample' },
] as const;
